#!/usr/bin/env php
<?php

use BaseTree\Tests\Fake\Integration\Laravel\ConsoleKernel;
use Illuminate\Contracts\Console\Kernel;

define('LARAVEL_START', microtime(true));

require __DIR__ . '/../../../../vendor/autoload.php';

$app = require_once __DIR__ . '/../../../../vendor/laravel/laravel/bootstrap/app.php';

$app->singleton(Kernel::class, ConsoleKernel::class);
$kernel = $app->make(Illuminate\Contracts\Console\Kernel::class);

$status = $kernel->handle(
    $input = new Symfony\Component\Console\Input\ArgvInput,
    new Symfony\Component\Console\Output\ConsoleOutput
);

$kernel->terminate($input, $status);

exit($status);

